language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm

env:
    - TARANTOOL_CLIENT=pure
    - TARANTOOL_CLIENT=pecl

matrix:
    allow_failures:
        - php: hhvm
        - env: TARANTOOL_CLIENT=pecl
    exclude:
        - php: hhvm
          env: TARANTOOL_CLIENT=pecl
    fast_finish: true

before_install:
    - curl http://tarantool.org/dist/public.key | sudo apt-key add -
    - echo "deb http://tarantool.org/dist/master/ubuntu `lsb_release -c -s` main" | sudo tee -a /etc/apt/sources.list.d/tarantool.list
    - sudo apt-get update

install:
    - sudo apt-get -y install tarantool

    - >
        bash -c 'if [[ $TRAVIS_PHP_VERSION != hhvm* ]]; then
            pecl install msgpack-0.5.6;
        else
            tests/install_msgpack_hhvm.sh;
        fi;'

    - >
        bash -c 'if [[ $TARANTOOL_CLIENT == pecl ]]; then
            git clone https://github.com/tarantool/tarantool-php.git;
            cd tarantool-php;
            phpize && ./configure;
            make;
            sudo make install;
            cd ..;
            printf "extension = tarantool.so\n" >> ~/.phpenv/versions/$TRAVIS_PHP_VERSION/etc/php.ini;
        fi;'

    - composer install

before_script:
    - sudo cp ./tests/Integration/instance.lua /etc/tarantool/instances.enabled
    - sudo tarantoolctl start instance
    - >
        for i in `seq 1 10`; do
            if sudo tarantoolctl status instance; then
                break;
            fi;
            sleep 1;
        done

script:
    - >
        bash -c 'if [[ $TARANTOOL_CLIENT == pecl ]]; then
            phpunit --testsuite Integration --exclude-group pureonly;
        elif [[ $TRAVIS_PHP_VERSION == 5.6 ]]; then
            phpunit --coverage-clover coverage.clover;
        else
            phpunit;
        fi;'

after_script:
    # code-coverage for scrutinizer-ci
    - >
        bash -c 'if [[ -f coverage.clover ]]; then
            wget https://scrutinizer-ci.com/ocular.phar;
            php ocular.phar code-coverage:upload --format=php-clover coverage.clover;
        fi;'
