language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - hhvm

env:
    - TARANTOOL_CLIENT=pecl
    - TARANTOOL_PACKER=pecl
    - TARANTOOL_PACKER=pecl_lite

matrix:
    exclude:
        - php: hhvm
          env: TARANTOOL_CLIENT=pecl
        - php: hhvm
          env: TARANTOOL_PACKER=pecl
    allow_failures:
        - php: 7.0
        - php: hhvm
        - env: TARANTOOL_CLIENT=pecl
    fast_finish: true

before_install:
    - curl http://tarantool.org/dist/public.key | sudo apt-key add -
    - echo "deb http://tarantool.org/dist/1.6/ubuntu `lsb_release -c -s` main" | sudo tee -a /etc/apt/sources.list.d/tarantool.list
    - sudo apt-get update

install:
    - sudo apt-get -y install tarantool

    - >
        if [[ $TRAVIS_PHP_VERSION == 7.0 ]]; then
            git clone https://github.com/msgpack/msgpack-php.git;
            cd msgpack-php;
            git checkout php7;
            phpize && ./configure;
            make;
            sudo make install;
            cd ..;
            printf "extension = msgpack.so\n" >> ~/.phpenv/versions/$TRAVIS_PHP_VERSION/etc/php.ini;

            composer global require phpunit/phpunit-mock-objects:3.0.*@dev;
            composer global require sebastian/resource-operations:1.0.*@dev;
            composer global require phpunit/phpunit:5.0.*@dev;
            export PATH="~/.composer/vendor/bin:$PATH";
        elif [[ $TRAVIS_PHP_VERSION == hhvm* ]]; then
            tests/install_msgpack_hhvm.sh;
        else
            pecl install msgpack-0.5.6;
        fi

    - >
        if [[ $TARANTOOL_CLIENT == pecl ]]; then
            git clone https://github.com/tarantool/tarantool-php.git;
            cd tarantool-php;
            phpize && ./configure;
            make;
            sudo make install;
            cd ..;
            printf "extension = tarantool.so\n" >> ~/.phpenv/versions/$TRAVIS_PHP_VERSION/etc/php.ini;
        fi

    - composer install

before_script:
    - sudo cp ./tests/Integration/instance.lua /etc/tarantool/instances.enabled
    - sudo tarantoolctl start instance
    - >
        for i in `seq 1 10`; do
            if sudo tarantoolctl status instance; then
                break;
            fi;
            sleep 1;
        done

script:
    - >
        if [[ $TARANTOOL_CLIENT == pecl ]]; then
            phpunit --testsuite Integration --exclude-group pureonly;
        elif [[ $TRAVIS_PHP_VERSION == 5.6 ]]; then
            phpunit --coverage-clover coverage.clover;
        else
            phpunit;
        fi

after_script:
    # code-coverage for scrutinizer-ci
    - >
        if [[ -f coverage.clover ]]; then
            wget https://scrutinizer-ci.com/ocular.phar;
            php ocular.phar code-coverage:upload --format=php-clover coverage.clover;
        fi
